version: '2'
services:
  codeserver:
    build: .
    command: >
        sh -c "/app/entrypoint/codeserver.sh"

    volumes:
      - .:/app
      - bundle_path:/bundle
      - /app/frontend/node_modules
    ports:
      - "3000:3000" # frontend
      - "3001:3001" # backend
      - "8080:8080" # codeserver
    environment:
      - PASSWORD
      - BUNDLE_PATH=/bundle/vendor
volumes:
  bundle_path:
